apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8000
      name: auth-web-service
      targetPort: auth-w-deploy
  type: ClusterIP
