apiVersion: v1
kind: ConfigMap
metadata:
  name: pinger-config
  namespace: microservices
data:
  db_type: "postgres"
  postgres_db: "pinger"
---
apiVersion: v1
kind: Secret
metadata:
  name: pinger-secret
  namespace: microservices
type: Opaque
data:
  postgres_user: cm9vdA==
  postgres_password: cGFzc3dk
  connection_dsn: cG9zdGdyZXM6Ly9yb290OnBhc3N3ZEBwb3N0Z3Jlcy1waW5nZXI6NTQzMi9waW5nZXI/c3NsbW9kZT1kaXNhYmxl
