apiVersion: v1
kind: ConfigMap
metadata:
  name: pinger-config
  namespace: microservices
data:
  POSTGRES_DB: "pinger"
---
apiVersion: v1
kind: Secret
metadata:
  name: pinger-secret
  namespace: microservices
type: Opaque
data:
  POSTGRES_USER: cm9vdA==
  POSTGRES_PASSWORD: cGFzc3dk
