apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-config
  namespace: microservices
data:
  db_type: "postgres"
  postgres_db: "delivery"
---
apiVersion: v1
kind: Secret
metadata:
  name: delivery-secret
  namespace: microservices
type: Opaque
data:
  postgres_user: cm9vdA==
  postgres_password: cGFzc3dk
  connection_dsn: cG9zdGdyZXM6Ly9yb290OnBhc3N3ZEBwb3N0Z3Jlcy1kZWxpdmVyeTo1NDMyL2RlbGl2ZXJ5P3NzbG1vZGU9ZGlzYWJsZQ==
#echo -n 'postgres://root:passwd@postgres-delivery:5432/delivery?sslmode=disable' | base64