apiVersion: batch/v1
kind: Job
metadata:
  name: delivery-migrate-up
  namespace: microservices
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: delivery-migrate-up
          image: vladimirkostin/delivery:latest
          args:
            - "/bin/sh"
            - "-c"
            - "/opt/db/migrate -database=${CONNECTION_DSN} -path=/opt/db/migrations up"
          env:
            - name: CONNECTION_DSN
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: connection_dsn
      restartPolicy: OnFailure
  backoffLimit: 7