apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: microservices
data:
  db_type: "postgres"
  postgres_db: "order"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: microservices
type: Opaque
data:
  postgres_user: cm9vdA==
  postgres_password: cGFzc3dk
  connection_dsn: cG9zdGdyZXM6Ly9yb290OnBhc3N3ZEBwb3N0Z3Jlcy1vcmRlcjo1NDMyL29yZGVyP3NzbG1vZGU9ZGlzYWJsZQ==
#echo -n 'postgres://root:passwd@postgres-order:5432/order?sslmode=disable' | base64