apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
  labels:
    k8s-app: kube-state-metrics
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8000
      name: order-web
      targetPort: order-web-dep
  type: ClusterIP
