apiVersion: v1
kind: ConfigMap
metadata:
  name: store-config
  namespace: microservices
data:
  db_type: "postgres"
  postgres_db: "store"
---
apiVersion: v1
kind: Secret
metadata:
  name: store-secret
  namespace: microservices
type: Opaque
data:
  postgres_user: cm9vdA==
  postgres_password: cGFzc3dk
  connection_dsn: cG9zdGdyZXM6Ly9yb290OnBhc3N3ZEBwb3N0Z3Jlcy1zdG9yZTo1NDMyL3N0b3JlP3NzbG1vZGU9ZGlzYWJsZQ==
#echo -n 'postgres://root:passwd@postgres-store:5432/store?sslmode=disable' | base64