apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pinger-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-url: http://arch.homework/auth/verify
    nginx.ingress.kubernetes.io/auth-response-headers: X-Request-Id, X-User-Id, traceparent
  namespace: microservices
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /pc(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: pinger-service
              port:
                number: 8000

