apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-config
  namespace: microservices
data:
  db_type: "postgres"
  postgres_db: "notify"
---
apiVersion: v1
kind: Secret
metadata:
  name: notify-secret
  namespace: microservices
type: Opaque
data:
  postgres_user: cm9vdA==
  postgres_password: cGFzc3dk
  connection_dsn: cG9zdGdyZXM6Ly9yb290OnBhc3N3ZEBwb3N0Z3Jlcy1ub3RpZnk6NTQzMi9ub3RpZnk/c3NsbW9kZT1kaXNhYmxl
#echo -n 'postgres://root:passwd@postgres-notify:5432/notify?sslmode=disable' | base64