apiVersion: apps/v1
kind: Deployment
metadata:
    name: pinger-deployment
    labels:
      app: pinger
    namespace: microservices
spec:
    replicas: 2
    selector:
       matchLabels:
          app: pinger
    template:
       metadata:
          labels:
             app: pinger
       spec:
          containers:
          - name: pinger
            image: vladimirkostin/pinger:latest
            env:
              - name: PORT
                value: '8000'
              - name: DB_TYPE
                valueFrom:
                  configMapKeyRef:
                    name: pinger-config
                    key: DB_TYPE
              - name: CONNECTION_DSN
                valueFrom:
                  secretKeyRef:
                    name: pinger-secret
                    key: CONNECTION_DSN
            ports:
              - name: web
                containerPort: 8000
