apiVersion: apps/v1
kind: Deployment
metadata:
    name: pinger-deployment
    labels:
      app: pinger
    namespace: microservices
spec:
    replicas: 3
    selector:
       matchLabels:
          app: pinger
    template:
       metadata:
          labels:
             app: pinger
       spec:
          containers:
          - name: pinger
            image: vladimirkostin/pinger:latest
            command: ["/opt/pinger/pinger-app"]
            env:
              - name: PORT
                value: '8000'
              - name: DB_TYPE
                valueFrom:
                  configMapKeyRef:
                    name: pinger-config
                    key: db_type
              - name: CONNECTION_DSN
                valueFrom:
                  secretKeyRef:
                    name: pinger-secret
                    key: connection_dsn
            ports:
              - name: pinger-web-dep
                containerPort: 8000
              - name: metrics
                containerPort: 9090
