apiVersion: v1
kind: Service
metadata:
  name: pinger-service
  namespace: microservices
spec:
  selector:
    app: pinger
  ports:
    - protocol: TCP
      port: 8000
      targetPort: web
  type: NodePort
