controller:
  kind: DaemonSet
  reportNodeInternalIp: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: NodePort
  config:
    proxy-buffer-size: 16k
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: prometheus
      enabled: true
